MooSharpSolution/MooSharp/Models/ViewModels/AssignmentDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MooSharp.Models.ViewModels
{
	public class AssignmentDetailsViewModel
	{
		public int ID { get; set; }

		public string Title { get; set; }

		public int CourseID { get; set; }

		public int MilestoneID { get; set; }

		public string Description { get; set; }

		public List<MilestoneViewModel> Milestones { get; set; }

		public DateTime DueDate { get; set; }

		public string CourseTitle { get; set; }

	}
}

MooSharpSolution/MooSharp/Models/ViewModels/Students/CreateSubmissionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MooSharp.Models.ViewModels.Students
{
    /// <summary>
    /// This class creates a submission
    /// </summary>
    public class CreateSubmissionViewModel
	{
        /// <summary>
        /// Contains an id of the submission
        /// </summary>
        [Required]
		[Display(Name = "ID")]
		public int ID { get; set; }

        /// <summary>
        /// Contains an id of the milstone which
        /// the submission is being submitted to
        /// </summary>
        [Required]
		[Display(Name = "MilestoneID")]
		public int MilestoneID { get; set; }

        /// <summary>
        /// Contains an user id which is submitting
        /// the result
        /// </summary>
        [Required]
		[Display(Name = "UserID")]
		public string UserID { get; set; }

        /// <summary>
        /// The date and time of the submission
        /// </summary>
        [Required]
		[Display(Name = "Submission Date/Time")]
		public DateTime SubmissionDateTime { get; set; }

        /// <summary>
        /// A directory path that the submission goes to,
        /// once subitted
        /// </summary>
        [Required]
		[Display(Name = "Submission path")]
		public string SubmissionPath { get; set; }

        /// <summary>
        /// A general status of the submission
        /// Example: Time limit exceeded, wrong answer etc.
        /// </summary>
        [Required]
		[Display(Name = "Status")]
		public string Status { get; set; }
	}
}

MooSharpSolution/MooSharp/Models/ViewModels/Students/StudentIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MooSharp.Models.ViewModels.Students
{
    /// <summary>
    /// This class contains the information displayed
    /// on the student index page
    /// </summary>
	public class StudentIndexViewModel
	{
        /// <summary>
        /// A list of the students active assignments
        /// which are not due yet
        /// </summary>
        public List<AssignmentViewModel> ActiveAssignments { get; set; }

        /// <summary>
        /// A list of all the assignments that have been 
        /// </summary>
        public List<AssignmentViewModel> FinishedAssignments { get; set; }
        
        /// <summary>
        /// A list of all the courses which the student is assigned to
        /// </summary>
		public List<CourseViewModel> MyCourses { get; set; }
	}
}

MooSharpSolution/MooSharp/Models/ViewModels/Students/SubmissionResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MooSharp.Models.ViewModels.Students
{
    /// <summary>
    /// This class contains the information displayed
    /// in the Submission result page
    /// </summary>
	public class SubmissionResultsViewModel
	{
        /// <summary>
        /// Contains the id of the submission
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// Contains the id of the milestone that the
        /// submission is submitted to
        /// </summary>
        public int MilestoneID { get; set; }

        /// <summary>
        /// Contains the title of the main assignment 
        /// </summary>
        public string AssignmentTitle { get; set; }

        /// <summary>
        /// Contains the tite of the milestone
        /// </summary>
        public string MilestoneTitle { get; set; }

        /// <summary>
        /// Contains the user id which is submitting 
        /// the result
        /// </summary>
        public string UserID { get; set; }

        /// <summary>
        /// Contains the date and time of the submission
        /// </summary>
        public DateTime SubmissionDateTime { get; set; }
        
        /// <summary>
        /// A general status of the submission.
        /// Example: Wrong answer, compile error etc.
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// A bool function that determines if the
        /// submission compiled or not
        /// </summary>
        public bool Compiled { get; set; }

        /// <summary>
        /// The output of the compilation if it failed
        /// </summary>
        public string CompilerOutput { get; set; }

        /// <summary>
        /// A list that contains all the test cases of the submission
        /// </summary>
        public List<SubmissionTestCaseViewModel> SubmissionTestCases { get; set; }


	}
}

MooSharpSolution/MooSharp/Models/ViewModels/Students/SubmissionTestCaseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MooSharp.Models.ViewModels.Students
{
	public class SubmissionTestCaseViewModel
	{
		public int ID { get; set; }

		public int SubmissionID { get; set; }

		public bool WrongOutput { get; set; }

		public string Output { get; set; }

		public string ExpectedOutput { get; set; }

		public bool TimeLimitExceeded { get; set; }

		public bool MemoryError { get; set; }

		public string MemoryErrorOutput { get; set; }
	}
}

MooSharpSolution/MooSharp/Controllers/StudentsController.cs
using Microsoft.AspNet.Identity;
using MooSharp.Models.ViewModels.Students;
using MooSharp.Services;
using MooSharp.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MooSharp.Models.ViewModels;

namespace MooSharp.Controllers
{
	[AccessDeniedAttribute(Roles = "Students")]
	[Authorize(Roles = "Students")]
	public class StudentsController : Controller
    {
		private CoursesService _coursesService = new CoursesService();
		private AssignmentsService _assignmentsService = new AssignmentsService();
		private SubmissionsService _submissionsService = new SubmissionsService();
		private MilestonesService _milestonesService = new MilestonesService();
        // GET: Students
        public ActionResult Index()
        {
			var viewModel = new StudentIndexViewModel() {
				ActiveAssignments = _assignmentsService.GetActiveAssignments(User.Identity.GetUserId())
									.Where(x => DateTime.Compare(x.OpeningDate,DateTime.Today) <= 0).ToList(),
				FinishedAssignments = _assignmentsService.GetFinishedAssignments(User.Identity.GetUserId()),
				MyCourses = _coursesService.GetCoursesByUser(User.Identity.GetUserId())
				
			};
            return View(viewModel);
        }

		public ActionResult CreateSubmission(int? milestoneID) {
			if(!milestoneID.HasValue) {
				throw new HttpException(400, "Bad Request");
			}
			if (!_milestonesService.MilestoneIsInDbById(Convert.ToInt32(milestoneID))) {
				throw new HttpException(404, "Not Found");
			}
			var viewModel = new CreateSubmissionViewModel() {
				MilestoneID = Convert.ToInt32(milestoneID),
				UserID = User.Identity.GetUserId().ToString()
			};
			return View(viewModel);
		}

		[HttpPost]
		public ActionResult CreateSubmission(CreateSubmissionViewModel viewModel) {
			//Hugsanlega compile-a og fara yfir verkefni og skila því
			//Kalla í CreateSubmission í submissionService
			return null;
		}

		public ActionResult CourseDetails(int? id) {
			if (!id.HasValue) {
				throw new HttpException(400, "Bad Request");
			}
			if (!_coursesService.CourseIsInDbById(Convert.ToInt32(id))) {
				throw new HttpException(404, "Not Found");
			}

			var course = _coursesService.GetCourseById(Convert.ToInt32(id));
			course.Assignments.Sort((y, x) => DateTime.Compare(x.DueDate, y.DueDate));
			course.Assignments = course.Assignments
								.Where(x => DateTime.Compare(x.OpeningDate, DateTime.Today) <= 0).ToList();
			return View(course);
		}

		public ActionResult AssignmentDetails(int? assignmentID) {
			if (!assignmentID.HasValue) {
				//return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				throw new HttpException(400, "Bad Request");
			}
			if (!_assignmentsService.AssignmentIsInDbById(Convert.ToInt32(assignmentID))) {
				//throw new Exception("Not found");
				throw new HttpException(404, "Not Found");
			}

			var assignmentViewModel = _assignmentsService.GetAssignmentByID(Convert.ToInt32(assignmentID));

			var viewModel = new AssignmentDetailsViewModel() {
				CourseID = assignmentViewModel.CourseID,
				CourseTitle = assignmentViewModel.CourseTitle,
				Description = assignmentViewModel.Description,
				DueDate = assignmentViewModel.DueDate,
				ID = assignmentViewModel.ID,
				Milestones = assignmentViewModel.Milestones,
				Title = assignmentViewModel.Title
			};

			// Sort submissions by date and get current user's submissions
			foreach(MilestoneViewModel milestone in viewModel.Milestones) {
				milestone.Submissions.Sort((y, x) => DateTime.Compare(x.SubmissionDateTime, y.SubmissionDateTime));
				milestone.Submissions = milestone.Submissions.Where(x => x.UserID == User.Identity.GetUserId()).ToList();
			}

			return View(viewModel);
		}

		public ActionResult SubmissionResults(int submissionID) {
			var viewModel = _submissionsService.GetSubmissionById(submissionID);

			return View(viewModel);
		}
	}
}

MooSharpSolution/MooSharp/Controllers/SubmissionsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MooSharp.Models.ViewModels;
using MooSharp.Models.ViewModels.Students;
using MooSharp.Services;


namespace MooSharp.Controllers
{
    public class SubmissionsController : Controller
    {
		CoursesService _coursesService = new CoursesService();
		MilestonesService _milestonesService = new MilestonesService();
		AssignmentsService _assignmentsService = new AssignmentsService();
		SubmissionsService _submissionsService = new SubmissionsService();

		// GET: Submissions
		public ActionResult Index(){
            return View();
        }

		public ActionResult UploadSubmission(AssignmentDetailsViewModel viewModel, HttpPostedFileBase file) {
			var courseID = viewModel.CourseID;
			var assignmentID = viewModel.ID;
			var milestoneID = viewModel.MilestoneID;
			var userName = User.Identity.GetUserName();
			var courseTitle = _coursesService.GetCourseById(courseID).Title;
			var assignmentTitle = _assignmentsService.GetAssignmentByID(assignmentID).Title;
			var milestoneTitle = _milestonesService.GetMilestonetByID(milestoneID).Title;
			var extension = Path.GetExtension(file.FileName);

			string path = "";

			if (file.ContentLength > 0) {
				var fileName = Path.GetFileName(file.FileName);
				var mapPath = Server.MapPath(String.Format("~/App_Data/Submissions/{0}/{1}/{2}/{3}", 
															userName, 
															courseTitle + "_" + courseID, 
															assignmentID + "_" + assignmentTitle, 
															milestoneID + "_" + milestoneTitle));
				path = Path.Combine(mapPath, fileName);
				if (!Directory.Exists(mapPath)) {
					Directory.CreateDirectory(mapPath);
				}
				
				int i = 0;
				while (System.IO.File.Exists(path)) {
					if(i == 0) {
						path = path.Replace(extension, "(" + ++i + ")" + extension);
					}
					else {
						path = path.Replace("(" + i + ")" + extension, "(" + ++i + ")" + extension);
					}
				}
				file.SaveAs(path);
			}

			var submissionViewModel = new CreateSubmissionViewModel() {
				UserID = User.Identity.GetUserId(),
				MilestoneID = milestoneID,
				SubmissionDateTime = DateTime.Now,
				SubmissionPath = path
			};

			int submissionID = _submissionsService.CreateSubmission(submissionViewModel, extension);

			string exeFileFullPath = path.Replace(".cpp", ".exe");
			string objFileFullPath = path.Replace(".cpp", ".obj");
			
			if (System.IO.File.Exists(exeFileFullPath)) {
				System.IO.File.Delete(exeFileFullPath);
			}
			if (System.IO.File.Exists(objFileFullPath)) {
				System.IO.File.Delete(objFileFullPath);
			}

			return RedirectToAction("AssignmentDetails", "Students", new { assignmentID = assignmentID });
		}
		public ActionResult DisplayHistory(string userID) {
			var submissions = _submissionsService.GetSubmissionsByUser(userID);
			return View(submissions);
		}
	}
}

MooSharpSolution/MooSharp/Views/Students/AssignmentDetails.cshtml
@model MooSharp.Models.ViewModels.AssignmentDetailsViewModel

@using MooSharp.Models.ViewModels

@{
    ViewBag.Title = "AssignmentDetails";
}
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<h1> @Model.Title - @Model.CourseTitle</h1>
<hr />
<br />
<h3>Assignment Description</h3>
<p>@Model.Description</p>
<br />
<h3>Milestones</h3>
<br />

<div>
    <!-- Tab headers -->
    @if (Model.Milestones.Count > 0) {
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a data-target="@("#" + Model.Milestones[0].ID)" aria-controls="home" role="tab" data-toggle="tab">@("1. " + Model.Milestones[0].Title)</a></li>
            @for (var i = 1; i < Model.Milestones.Count; i++) {

                <li role="presentation"><a data-target="@("#" + Model.Milestones[i].ID)" aria-controls="home" role="tab" data-toggle="tab">@((i + 1) + ". " + Model.Milestones[i].Title)</a></li>

            }
        </ul>
        <!-- Tab headers end -->

        <!-- Tab content-->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="@Model.Milestones[0].ID">
                <br />
                <h4>Description</h4>
                <p>@Model.Milestones[0].Description</p>
                <br />
                @if (DateTime.Compare(Model.DueDate, DateTime.Now) >= 0) {
                    using (Html.BeginForm("UploadSubmission", "Submissions", FormMethod.Post, new { @class = "form form-horizontal", role = "form", enctype = "multipart/form-data" })) {
                        <label for="file">Upload file for this milestone:</label>
                        <input type="file" name="file" id="file" /> <br />
                        <input type="submit" class="btn btn-default" value="Submit" />
                        <input name="ID" id="ID" value="@Model.ID" hidden />
                        <input name="CourseID" id="CourseID" value="@Model.CourseID" hidden />
                        <input name="MilestoneID" id="MilestoneID" value="@Model.Milestones[0].ID" hidden />
                    }
                }
                else {
                    <p class="text-danger"> Due date has exceded</p>
                }
                <br />
                <!-- Submissions list -->
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Submission</th>
                            <th>Status</th>
                            <th>Submission time</th>
                        </tr>
                    </thead>
                    <tbody>

                    @{ var count = Model.Milestones[0].Submissions.Count;}
                    @for (var i = 0; i < Model.Milestones[0].Submissions.Count; i++) {
                        <tr>
                            <td>@Html.ActionLink("Submission " + count, "SubmissionResults", new { submissionID = Model.Milestones[0].Submissions[i].ID })</td>
                            <td>@Model.Milestones[0].Submissions[i].Status</td>
                            <td>@Model.Milestones[0].Submissions[i].SubmissionDateTime</td>
                        </tr>
                        count--;
                    }
                    </tbody>
                </table>
                @if (Model.Milestones[0].Submissions.Count == 0) {
                    <p class="text-danger">No submissions exist</p>
                }
            </div>
            <!-- Start of loop -->
            @for (var i = 1; i < Model.Milestones.Count; i++) {

                <div role="tabpanel" class="tab-pane" id="@Model.Milestones[i].ID">
                    <br />
                    <h4>Description</h4>
                    <p>@Model.Milestones[i].Description</p>
                    <br />

                    @if (DateTime.Compare(Model.DueDate, DateTime.Now) >= 0){

                        using (Html.BeginForm("UploadSubmission", "Submissions", FormMethod.Post, new { @class = "form form-horizontal", role = "form", enctype = "multipart/form-data" })) {
                        <label for="file">Upload file for this milestone:</label>
                        <input type="file" name="file" id="file" /> <br />
                        <input type="submit" class="btn btn-default" value="Submit" />
                        <input name="ID" id="ID" value="@Model.ID" hidden />
                        <input name="CourseID" id="CourseID" value="@Model.CourseID" hidden />
                        <input name="MilestoneID" id="MilestoneID" value="@Model.Milestones[i].ID" hidden />
                        }
                    }
                    else {
                        <p class="text-danger"> Due date has exceded</p>
                    }
                    <br />
                    <!-- Submissions list -->
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Submission</th>
                                <th>Status</th>
                                <th>Submission time</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ var count2 = Model.Milestones[i].Submissions.Count;}
                            @for (var j = 0; j < Model.Milestones[i].Submissions.Count; j++) {
                                <tr>
                                    <td>@Html.ActionLink("Submission " + count, "SubmissionResults", new { submissionID = Model.Milestones[0].Submissions[i].ID })</td>
                                    <td>@Model.Milestones[i].Submissions[j].Status</td>
                                    <td>@Model.Milestones[i].Submissions[j].SubmissionDateTime</td>
                                </tr>count2--;
                            }
                        </tbody>
                    </table>
                    @if (Model.Milestones[i].Submissions.Count == 0) {
                        <p class="text-danger">No submissions exist</p>
                    }
                </div>
    }
        </div>
    }
    else {
        <p class="text-danger">No milestones exist for this assignment</p>
    }
    <!-- Tab content end -->
</div>

MooSharpSolution/MooSharp/Views/Students/CourseDetails.cshtml
@model MooSharp.Models.ViewModels.CourseViewModel
@using System;
@{
    ViewBag.Title = "CourseDetails";
}

<h1> @Model.Title</h1>
<hr />

<h4> @Model.CourseNumber</h4>
<br />

<h3>Active Assignments</h3>
<table class="table table-condensed">
    <thead>
        <tr>
            <th>Assignment Name</th>
            <th>Description</th>
            <th>Closing Time</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Assignments.Count; i++) {
            if (DateTime.Compare(Model.Assignments[i].DueDate, DateTime.Today) >= 0) {
                <tr>
                    <td>@Html.ActionLink(Model.Assignments[i].Title, "AssignmentDetails", new { assignmentID = Model.Assignments[i].ID })</td>
                    <td>@Model.Assignments[i].Description</td>
                    <td>@Model.Assignments[i].DueDate.ToString("dddd, dd. MMMM kl.HH:mm")</td>
                </tr>
}
        }

    </tbody>
</table>
<h3>Finished Assignments</h3>
<table class="table table-condensed" id="teacher">
    <thead>
        <tr>
            <th>Assignment Name</th>
            <th>Description</th>
            <th>Closing Time</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Assignments.Count; i++) {
            if (DateTime.Compare(Model.Assignments[i].DueDate, DateTime.Today) < 0) {
                <tr>
                    <td>@Html.ActionLink(Model.Assignments[i].Title, "AssignmentDetails", new { assignmentID = Model.Assignments[i].ID })</td>
                    <td>@Model.Assignments[i].Description</td>
                    <td>@Model.Assignments[i].DueDate.ToString("dddd, dd. MMMM kl.HH:mm")</td>
                </tr>
}
        }

    </tbody>
</table>

@section Copyright {
    <hr />
    <p>&copy; @DateTime.Now.Year - MooSharp</p>
}

MooSharpSolution/MooSharp/Views/Students/Index.cshtml
@model MooSharp.Models.ViewModels.Students.StudentIndexViewModel
@using MooSharp.Models.ViewModels
@{
    ViewBag.Title = "Student Home Page";
}

<h2>@ViewBag.Title</h2>
<hr />
<h3>Active assignments</h3>
<hr />
<div class="row">
    @foreach (AssignmentViewModel assignment in Model.ActiveAssignments.Take(3)) {

        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="@Url.Action("AssignmentDetails", "Students", new { assignmentID = assignment.ID })">
                        <h4>@Model.MyCourses.Where(x => x.ID == assignment.CourseID).FirstOrDefault().Title</h4>
                        <h5>@assignment.Title</h5>
                    </a>
                </div>
                <div class="panel-body">
                    <div>
                        <p><strong>Course</strong></p>
                            <p> @Model.MyCourses.Where(x => x.ID == assignment.CourseID).FirstOrDefault().Title</p>
                        <p><strong>Due date</strong></p>
                        <p> @(assignment.DueDate.ToString("dddd, dd. MMMM yyyy"))</p>
                        <p>@(assignment.DueDate.ToString("kl.HH:mm"))</p>  
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<h3>Finished Assignments</h3>
<hr />
<div class="row">
    @foreach (AssignmentViewModel assignment in Model.FinishedAssignments.Take(3)) {

        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="@Url.Action("AssignmentDetails", "Students", new { assignmentID = assignment.ID })">
                        <h4>@Model.MyCourses.Where(x => x.ID == assignment.CourseID).FirstOrDefault().Title</h4>
                        <h5>@assignment.Title</h5>
                    </a>
                </div>
                <div class="panel-body">
                        <p><strong>Course</strong></p>
                        <p> @Model.MyCourses.Where(x => x.ID == assignment.CourseID).FirstOrDefault().Title</p>
                        <p><strong>Due date</strong></p>
                        <p> @(assignment.DueDate.ToString("dddd, dd. MMMM yyyy"))</p>
                        <p>@(assignment.DueDate.ToString("kl.HH:mm"))</p>  
                </div>
            </div>
        </div>

    }
</div>

@section Copyright {
    <br />
    <br />
    <br />
    <hr />
    <p>&copy; @DateTime.Now.Year - MooSharp</p>
}

MooSharpSolution/MooSharp/Views/Students/SubmissionResults.cshtml
@model MooSharp.Models.ViewModels.Students.SubmissionResultsViewModel
@using MooSharp.Models.ViewModels

@{
    ViewBag.Title = "SubmissionResults";
}

<h1>Submission Results</h1>
<hr />

<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<h2> @Model.AssignmentTitle</h2>
<h3>Milestone: @Model.MilestoneTitle</h3>
<hr />
@if (Model.Compiled == false) {
    <p>Compile failed:</p>
    <p class="text-danger">@Model.CompilerOutput</p>
}
else {
<p class="text-success">Compile succeeded</p>
<br />

<div>
    <!-- Tab headers-->
    @if (Model.SubmissionTestCases.Count > 0) {
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a data-target="@("#" + Model.SubmissionTestCases[0].ID)" aria-controls="home" role="tab" data-toggle="tab">Test case 1</a></li>
            @for (var i = 1; i < Model.SubmissionTestCases.Count; i++) {

                <li role="presentation"><a data-target="@("#" + Model.SubmissionTestCases[i].ID)" aria-controls="home" role="tab" data-toggle="tab">@("Test case" + i+1)</a></li>

            }
        </ul>
    <!-- Tab headers end-->

    <!-- Tab Content -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="@Model.SubmissionTestCases[0].ID">
                <br />
                <h4>Time limit:</h4>
                @if (@Model.SubmissionTestCases[0].TimeLimitExceeded == true) {
                    <p class="text-danger">Time limit exceeded</p>
                }
                else {
                    <p class="text-success">Execution was within the time limit</p>
                    <hr />
                    <h4>Output:</h4>
                    if(Model.SubmissionTestCases[0].WrongOutput == true) {
                        <p class="text-danger">Wrong Output. See output below</p>
                            <div class="col-md-6">
                                <h5><strong>Obtained output</strong></h5>
                            </div>
                            <div class="col-md-6">
                                <h5><strong>Expected Output</strong></h5>
                            </div>
                            <div class="well col-md-6">
                                @Model.SubmissionTestCases[0].Output
                            </div>
                            <div class="well col-md-6">
                                @Model.SubmissionTestCases[0].ExpectedOutput
                            </div>
}
                    else {
                        <p class="text-success">Output was correct. Congratulations!</p>
                    }
                    <hr />
                }

            </div>
            @for (var i = 1; i < Model.SubmissionTestCases.Count; i++) {

                <div role="tabpanel" class="tab-pane" id="@Model.SubmissionTestCases[i].ID">
                    <br />

                </div>
            }
        </div>
    }
    else {
        <p class="text-danger">No submissions exist for this assignment</p>
    }
    <!-- Tab Content End -->
</div>
}