MooSharpSolution/MooSharp/Controllers/NavigationController.cs
using Microsoft.AspNet.Identity;
using MooSharp.Models.ViewModels.Students;
using MooSharp.Models.ViewModels.Teachers;
using MooSharp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MooSharp.Controllers
{
    public class NavigationController : Controller
    {
        private CoursesService _coursesService = new CoursesService();

		[ChildActionOnly]
		public ActionResult SideBar() {
			if (User.IsInRole("Administrators")) {
				return PartialView("AdminSideBar");
			}
			if (User.IsInRole("Teachers")) {
				var viewModel = new TeacherIndexViewModel() {
					MyCourses = _coursesService.GetCoursesByUser(User.Identity.GetUserId())
				};
				return PartialView("TeacherSideBar", viewModel);
			}
            if (User.IsInRole("Students")) {
                var viewModel = new StudentIndexViewModel()
                {
                    MyCourses = _coursesService.GetCoursesByUser(User.Identity.GetUserId())
                };

                return PartialView("StudentSideBar", viewModel);
            }
			return new EmptyResult();
		}
	}
}

MooSharpSolution/MooSharp/Views/Shared/NotFound.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "NotFound";
}

@{
    var r = new Random();
    var start = r.Next(450);
    var link = "https://youtube.com/embed/GquEnoqZAK0?start=" + start + "&enablejsapi=1&autoplay=1&loop=1&playlist=GquEnoqZAK0&controls=0&showinfo=0&autohide=1&iv_load_policy=3&modestbranding=1";
    //var link = "https://youtube.com/embed/bzmAaJtnKtQ?start=" + start + "&enablejsapi=1&autoplay=1&loop=1&playlist=ht2TigJp88w&controls=0&showinfo=0&autohide=1&iv_load_policy=3&modestbranding=1";
}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript">
    $('.navbar').hide();
    $('footer').hide();
    $(window).load(function () {
        $('#login-modal').modal('show');
        document.getElementById("#ytplayer").muted = true;
    });
</script>

<div id="youtube-background">
    <iframe id="ytplayer" frameborder="0" height="120%" width="120%" src="@link" volume="0"></iframe>
</div>
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false" style="display: none;">
    <div class="modal-dialog">
        <div class="loginmodal-container" id="access-modal">
            <section id="loginForm">
                <h2>Page Not Found</h2>
                <p>The page you requested could not be found.</p>
                <div id="access-buttons">
                    <button type="button" class="btn btn-default">@Html.ActionLink("Go back to home page", "Index", "Home")</button>
                </div>
            </section>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MooSharpSolution/MooSharp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="icon"
          type="image/x-icon"
          href="~/Static/img/favicon.png">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/bootstrap-changes.css")
    <!--TODO: Setja inn í Scripts.Render bundle-->
    <script src="https://use.fontawesome.com/e912a922a3.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
</head>
<body>
@if (Request.IsAuthenticated) {
    <div id="navbar"class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header"> 
                    <a href="~/home/index"><p class="moosharp-logo">MooSharp</p></a>   
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
         
                <!-- @Html.ActionLink("MooSharp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }) -->
            </div>
            <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <!--<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>-->
                    </ul>
                    @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <!--left-->
            <div class="col-md-3" id="leftCol">
                <ul class="nav nav-stacked" id="sidebar">
                    @Html.Action("SideBar", "Navigation")
                </ul>
            </div><!--/left-->
            <!--right-->
            <div class="col-md-9">
                @RenderBody()
            </div><!--/right-->
        </div><!--/row-->
        <footer>
            @RenderSection("Copyright", required: false)
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        /* activate sidebar */
        $('#sidebar').affix({
            offset: {
                top: 0
            }
        });

        /* activate scrollspy menu */
        var $body = $(document.body);
        var navHeight = $('.navbar').outerHeight(true) + 10;

        $body.scrollspy({
            target: '#leftCol',
            offset: navHeight
        });

        /* smooth scrolling sections */
        $('a[href*=#]:not([href=#])').click(function () {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top - 50
                    }, 1000);
                    return false;
                }
            }
        });
    </script>
}
else {
    <div class="container body-content">
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
}
</body>
</html>