MooSharpSolution/MooSharp/Models/ViewModels/Admins/ConnectTeacherToCourseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MooSharp.Models.Entities;

namespace MooSharp.Models.ViewModels.Admins
{
    /// <summary>
    /// This class connects teachers by username to a certain course
    /// </summary>
    public class ConnectTeacherToCourseViewModel
	{
        /// <summary>
        /// CourseID is required to find a certain course
        /// </summary>
        [Required]
		[Display(Name = "CourseID")]
		public int CourseID { get; set; }

        /// <summary>
        /// UserID is required to find a certain teacher
        /// </summary>
        [Required]
		[Display(Name = "UserID")]
		public string UserID { get; set; }

        /// <summary>
        /// The title of the course that the teacher will be assigned to
        /// </summary>
        public string CourseTitle { get; set; }

        /// <summary>
        /// A list that holds all the teachers 
        /// </summary>
        public List<UserViewModel> AllTeachers { get; set; }
	}
}

MooSharpSolution/MooSharp/Models/ViewModels/Admins/ConnectUserToCourseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MooSharp.Models.Entities;

namespace MooSharp.Models.ViewModels.Admins {

    /// <summary>
    /// This class connects a certain user to a certain course
    /// </summary>
    public class ConnectUserToCourseViewModel {

        /// <summary>
        /// Contains a CourseID which is required to find a certain course
        /// </summary>
        [Required]
		[Display(Name = "CourseID")]
		public int CourseID { get; set; }

        /// <summary>
        /// Contains UserID which is required
        /// </summary>
        [Required]
		[Display(Name = "UserID")]
		public string UserID { get; set; }

        /// <summary>
        /// A list that holds all courses
        /// </summary>
        public List<CourseViewModel> AllCourses { get; set; }

        /// <summary>
        /// A list that holds all the users
        /// </summary>
        public List<UserViewModel> AllUsers { get; set; }
	}
}

MooSharpSolution/MooSharp/Models/ViewModels/Admins/CreateCourseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MooSharp.Models.ViewModels.Admins
{
	public class CreateCourseViewModel
	{
		/// <summary>
		/// Contains the course number which can be both alpha and numerical characters.
		/// Example: "T-220-VLN2".
		/// </summary>
		[Required]
		[Display(Name = "CourseNumber")]
		public string CourseNumber { get; set; }

		/// <summary>
		/// Contains the title of the course.
		/// Example: "Verklegt námskeið 2"
		/// </summary>
		[Required]
		[Display(Name = "Name")]
		public string Name { get; set; }
	}
}

MooSharpSolution/MooSharp/Models/ViewModels/Admins/CreateUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MooSharp.Models.ViewModels.Admins
{
    /// <summary>
    /// This class creates a new user
    /// </summary>
    public class CreateUserViewModel
	{
        /// <summary>
        /// Contains a username
        /// </summary>
        [Required]
		[Display(Name = "Username")]
		public string UserName { get; set; }

        /// <summary>
        /// Contains the email address of the user
        /// Example: user@example.com
        /// </summary>
        [Required]
		[EmailAddress]
		[Display(Name = "Email")]
		public string Email { get; set; }

        /// <summary>
        /// Contains a password that has to 
        /// be at least 6 characters long
        /// </summary>
        [Required]
		[StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
		[DataType(DataType.Password)]
		[Display(Name = "Password")]
		public string Password { get; set; }

        /// <summary>
        /// A user must confirm his password by 
        /// entering it again
        /// </summary>
        [DataType(DataType.Password)]
		[Display(Name = "Confirm password")]
		[Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
		public string ConfirmPassword { get; set; }

        /// <summary>
        /// A role must be assigned to each user.
        /// Example: Student, Teacher, Admin
        /// </summary>
        public string Roles { get; set; }
	}
}

MooSharpSolution/MooSharp/Controllers/AdminsController.cs
using Microsoft.AspNet.Identity;
using MooSharp.Models;
using MooSharp.Models.ViewModels;
using MooSharp.Models.ViewModels.Admins;
using MooSharp.Services;
using MooSharp.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MooSharp.Controllers
{
	/// <summary>
	/// This class handles all control for Admins.
	/// Example: Create course, create user.
	/// </summary>
	[AccessDeniedAttribute(Roles = "Administrators")]
	[Authorize(Roles = "Administrators")]
	public class AdminsController : Controller
    {
		/// <summary>
		/// Instance of CoursesService for Admin to be able to work with Courses.
		/// </summary>
		private CoursesService _coursesService = new CoursesService();
		/// <summary>
		/// Instance of UsersService for Admin to be able to work with Users.
		/// </summary>
		private UsersService _usersService = new UsersService();

		/// <summary>
		/// Returns Index view with AdminIndexViewModel.
		/// </summary>
		public ActionResult Index() {
			var viewmodel = new AdminIndexViewModel() {
				AllCourses = _coursesService.GetAllCourses(),
				AllUsers = _usersService.GetAllUsers()
			};
            return View(viewmodel);
        }

		/// <summary>
		/// Returns a view with a form to be filled out to create a course
		/// </summary>
		public ActionResult CreateCourse() {
			return View();
		}

		/// <summary>
		/// Createcourse gets a viewmodel with information about a new course and 
		/// sends that info to CourseService to be added
		/// </summary>
		[HttpPost]
		public ActionResult CreateCourse(CreateCourseViewModel viewModel) {

			if (ModelState.IsValid) {
				_coursesService.Create(viewModel);
				return RedirectToAction("Index");
			}
			return View(viewModel);
		}

		/// <summary>
		/// Returns CreateUser view.
		/// </summary>
		public ActionResult CreateUser() {
			return View();
		}

		/// <summary>
		/// Takes in CreateUserViewModel that has been filled in by Admin and creates
		/// a new user with that information.
		/// </summary>
		[HttpPost]
		public ActionResult CreateUser(CreateUserViewModel viewModel) {
			// TODO: taka a móti forminu úr CreatUser og senda ViewModel í UserService CreateUser fallið
			if (ModelState.IsValid) {
				if (_usersService.CreateUser(viewModel)) {
					return RedirectToAction("Index");
				}
				else {
					ModelState.AddModelError("", "Creating User has failed, please try again.");
				}
			}
			return View(viewModel);
		}

		/// <summary>
		/// Returns ConnectUserToCourseViewModel.
		/// </summary>
		public ActionResult ConnectUserToCourse() {

			var viewModel = new ConnectUserToCourseViewModel() {
				AllCourses = _coursesService.GetAllCourses(),
				AllUsers = _usersService.GetAllUsers()
			};

			return View(viewModel);
		}

		/// <summary>
		/// Connects User to course.
		/// </summary>
		[HttpPost]
		public ActionResult ConnectUserToCourse(ConnectUserToCourseViewModel viewModel) {

			if (!_coursesService.ConnectUserToCourse(viewModel.UserID, viewModel.CourseID)) {
				viewModel.AllCourses = _coursesService.GetAllCourses();
				viewModel.AllUsers = _usersService.GetAllUsers();
				ModelState.AddModelError("", "User is already connected to this course");
				return View(viewModel);
			}

			return RedirectToAction("Index");
		}

		/// <summary>
		/// Returns ConnectTeacherToCourseViewModel.
		/// </summary>
		public ActionResult ConnectTeacherToCourse(int? courseID) {
			if (!courseID.HasValue) {
				throw new HttpException(400, "Bad Request");
			}
			if (!_coursesService.CourseIsInDbById(Convert.ToInt32(courseID))) {
				throw new HttpException(404, "Not Found");
			}
			var id = Convert.ToInt32(courseID);

			var viewModel = new ConnectTeacherToCourseViewModel() {
				CourseID = id,
				CourseTitle = _coursesService.GetCourseById(id).Title,
				AllTeachers = _usersService.GetAllTeachers()
			};

			return View(viewModel);
		}

		/// <summary>
		/// Connects TeacherToCourse.
		/// </summary>
		[HttpPost]
		public ActionResult ConnectTeacherToCourse(ConnectTeacherToCourseViewModel viewModel) {
			if (!_coursesService.ConnectUserToCourse(viewModel.UserID, viewModel.CourseID)) {
				ModelState.AddModelError("", "Teacher is already connected to this course");
				return View(viewModel);
			}

			return RedirectToAction("Index");
		}
	}
}

MooSharpSolution/MooSharp/Views/Admins/AdminSideBar.cshtml
<h4>@Html.ActionLink("Home", "Index", "Home")</h4>
<hr />
<li>@Html.ActionLink("Create Course", "CreateCourse", "Admins")</li>
<li>@Html.ActionLink("Create User", "CreateUser", "Admins")</li>
<li>@Html.ActionLink("Connect Users to Courses", "ConnectUserToCourse", "Admins")</li>
<hr />

MooSharpSolution/MooSharp/Views/Admins/ConnectTeacherToCourse.cshtml
@model MooSharp.Models.ViewModels.Admins.ConnectTeacherToCourseViewModel
@{
    ViewBag.Title = "ConnectUserToCourse";
}

<h2>Connect a Teacher to @Model.CourseTitle</h2>
<hr />
<div class="col-lg-6">
    @using (Html.BeginForm("ConnectTeacherToCourse", "Admins", FormMethod.Post, new { @class = "form form-horizontal", role = "form" })) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            <input value="@Model.CourseID" name="courseID" hidden />
            <label for="UserID" class="col-md-4 control-label" id="userlistlabel">User</label>
            <div class="col-md-8">
                <select id="UserID" name="UserID" class="form-control">
                    @for (var i = 0; i < Model.AllTeachers.Count; i++) {
                        <option value="@Model.AllTeachers[i].userId">@Model.AllTeachers[i].username (@Model.AllTeachers[i].roles.FirstOrDefault())</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Connect Teacher to Course" />
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MooSharpSolution/MooSharp/Views/Admins/ConnectUserToCourse.cshtml
@model MooSharp.Models.ViewModels.Admins.ConnectUserToCourseViewModel
@{
    ViewBag.Title = "ConnectUserToCourse";
}

<h2>ConnectUserToCourse</h2>
<hr />
<div class="col-lg-6">
@using (Html.BeginForm("ConnectUserToCourse", "Admins", FormMethod.Post, new { @class = "form form-horizontal", role = "form" })) {
    @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            <label for="courselist" class="col-md-4 control-label" id="courselistlabel">Course</label>
            <div class="col-md-8">
                <select id="CourseID" name="CourseID" class="form-control">
                    @for (int i = 0; i < Model.AllCourses.Count; i++) {
                        <option value="@Model.AllCourses[i].ID">@Model.AllCourses[i].Title</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="userlist" class="col-md-4 control-label" id="userlistlabel">User</label>
            <div class="col-md-8">
                <select id="UserID" name="UserID" class="form-control">
                    @for (var i = 0; i < Model.AllUsers.Count; i++) {
                        <option value="@Model.AllUsers[i].userId">@Model.AllUsers[i].username (@Model.AllUsers[i].roles.FirstOrDefault())</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Connect User to Course" />
            </div>
        </div>
        }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MooSharpSolution/MooSharp/Views/Admins/CreateCourse.cshtml
@model MooSharp.Models.ViewModels.Admins.CreateCourseViewModel
@{
    ViewBag.Title = "CreateCourse";
}

<h2>CreateCourse</h2>
<hr />
<div class="col-lg-6">
    @using (Html.BeginForm("CreateCourse", "Admins", FormMethod.Post, new { @class = "form form-horizontal", role = "form" })) {
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseNumber, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.CourseNumber, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Create Course" />
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MooSharpSolution/MooSharp/Views/Admins/CreateUser.cshtml
@model MooSharp.Models.ViewModels.Admins.CreateUserViewModel
@{
    ViewBag.Title = "Create User";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("CreateUser", "Admins", FormMethod.Post, new { @class = "form form-horizontal", role = "form" })) {
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.UserName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.UserName, new { @class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        <label for="roles" class="col-md-2 control-label" id="role-label">Roles</label>
        <div class="col-md-10">
            <select class="form-control" id="roles" name="roles">
                <option value="Administrators">Administrator</option>
                <option value="Teachers">Teacher</option>
                <option value="Students">Student</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create User" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MooSharpSolution/MooSharp/Views/Admins/Index.cshtml
@model MooSharp.Models.ViewModels.Admins.AdminIndexViewModel

@{
    ViewBag.Title = "Admin Home Page";
}

<h2>@ViewBag.Title</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3>Courses <a href="@Url.Content("~/Admins/CreateCourse")"><button type="button" class="btn btn-default">Create Course</button></a> </h3></div> 
            <div class="panel-body">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>Course</th>
                            <th>Course Number</th>
                            <th>Teachers</th>
                        </tr>
                    </thead>
                    <tbody>                        
                        @for (var i = Model.AllCourses.Count -1; i >= 0; i--) {
                            <tr>
                                <td>@Model.AllCourses[i].Title</td>
                                <td>@Model.AllCourses[i].CourseNumber</td>
                                <td>
                                    @if (Model.AllCourses[i].Teachers.Count == 0) {
                                        using (Html.BeginForm("ConnectTeacherToCourse", "Admins", FormMethod.Get, new { @class = "form form-horizontal", role = "form" })) {
                                        <div class="form-group">
                                                <input value="@Model.AllCourses[i].ID" name="courseID" hidden />
                                                <input type="submit" class="btn btn-default" value="Add Teacher to Course" />
                                        </div>}}
                                    else {
                                        for (var j = 0; j < Model.AllCourses[i].Teachers.Count; j++) {
                                            @Model.AllCourses[i].Teachers[j].username;
                                            if(!(j + 1 == Model.AllCourses[i].Teachers.Count)) {
                                            <text>, &nbsp;</text>
                                                }
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h3>Users <a href="@Url.Content("~/Admins/CreateUser")"><button class="btn btn-default">Create User</button></a> </h3></div>
            <div class="panel-body">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>User Name</th>
                            <th>Email</th>
                            <th>Roles</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (var i = 0; i < Model.AllUsers.Count; i++) {
                            <tr>
                                <td>@Model.AllUsers[i].username</td>
                                <td>@Model.AllUsers[i].email</td>
                                <td>
                                    @for (var j = 0; j < Model.AllUsers[i].roles.Count; j++) { 
                                        @Model.AllUsers[i].roles[j] 
                                        if(!(j + 1 == Model.AllUsers[i].roles.Count)) {
                                            <text>, &nbsp;</text>
    }
}
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">
    window.addEventListener("keydown", checkKeyPressed, false);

    function checkKeyPressed(e) {
        if (e.keyCode == "18") {
            isCtrl = true;
        }
        if (e.keyCode == "71" && isCtrl == true) {
            window.location ='@Url.Content("~/Account/GandalfEasterEgg")';
        }
    }
</script>

@section Copyright {
    <hr />
    <p>&copy; @DateTime.Now.Year - MooSharp</p>
}